apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: DOCKER_IMAGE
        ports:
        - containerPort: 3000 # เปลี่ยนเป็น 3000 เพื่อให้ตรงกับ Next.js