name: Deploy to AWS ECS 

on:
  push:
    branches: [main ,dev]
      
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/git-actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin public.ecr.aws/o4v6k8p8
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker tag my-scaleup-repo:latest ${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

          
      - name: ECS Task Update 
        run: |
          aws ecs update-service \
            --cluster scaleup-node-cluster \
            --service my-node-task-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
  